In [1]:
# Standard modules
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

# Other modules
import sys
import time
import glob
import os

# Import suftware
sys.path.append('../../')
import suftware as sw

In [2]:
# Specify directories
raw_data_file = '../data/raw/who_data_2017.xlsx'
output_dir = '../data'

# Remove all previous WHO output files
files_to_remove = glob.glob('%s/who.*.txt'%output_dir)
for file in files_to_remove:
    os.remove(file)

In [3]:
# Load raw data
df = pd.read_excel(raw_data_file, header=None, skiprows=4)
df.head(10)

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,Description,Total population,"Life expectancy, \nmale","Life expectancy, \nfemale",Life expectancy,Healthy life expectancy,Maternal mortality,Attended births,Under-five mortality,Neonatal moraltiy,...,Wasting in children,Overweight children,Clean water,Sanitation,Clean fuels,Particulate matter in air,Annual natural diaster \ndeaths,Homicide mortality,Deaths from major \nconflicts,Cause of death known
1,Units,thousands,years,years,years,years,"per 100,000 live births",percent,"per 1,000 live births","per 1,000 live births",...,percent,percent,percent of population,percent of population,percent of population,micrograms per cubi meter,"per 100,000","per 100,000","per 100,000",percent
2,Dataset,population,life_expectancy_male,life_expectancy_female,life_expectancy,life_expectancy_healthy,maternal_mortality,attended_births,under_five_mortality,neonatal_moratlity,...,child_wasting,child_overweight,clean_water,sanitation,clean_fuels,particulate_matter,natural_disasters,homicide,conflict_deaths,cause_of_death_known
3,Years,2015,2015,2015,2015,2015,2015,2005â€“2016,2015,2015,...,2005-2016,2005-2016,2015,2015,2014,2014,2011-2015,2015,2011-2015,2005-2015
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Afghanistan,32527,59.3,61.9,60.5,52.2,396,51,91.1,35.5,...,9.5,5.4,55,32,17,63.4,0.8,7.0,40.9,NaN
6,Albania,2897,75.1,80.7,77.8,68.8,29,99,14.0,6.2,...,9.4,23.4,95,93,67,17.1,0.0,4.1,0.1,76
7,Algeria,39667,73.8,77.5,75.6,66.0,140,97,25.5,15.5,...,4.1,12.4,84,88,95,25.1,0.1,4.2,1.0,NaN
8,Andorra,70,NaN,NaN,NaN,NaN,NaN,NaN,2.8,1.4,...,NaN,NaN,100,100,95,10.5,NaN,NaN,NaN,100
9,Angola,25022,50.9,54.0,52.4,45.8,477,47,156.9,48.7,...,4.9,3.3,49,52,48,42.4,0.1,9.6,0.0,NaN

In [4]:
descriptions = df.iloc[0,1:].values
units = df.iloc[1,1:].values
names = df.iloc[2,1:].values
years = df.iloc[3,1:].values
num_datasets = df.shape[1]-1

for i in range(num_datasets):
    
    # Extract data values
    values = df.iloc[5:,i+1].values.astype(float)
    description_str = repr(descriptions[i] + ' (%s)'%years[i])
    
    # Format file contentx
    header = '# "description": %s\n# "name": "%s"\n# "units": "%s"\n'%\
                (description_str, names[i], units[i])
    contents = ''.join(['%.1f\n'%x for x in values])
    
    # Write file
    file_name = '%s/who.%s.txt'%(output_dir,names[i])
    print('Writing %s'%file_name)
    with open(file_name,'w') as f:
        f.write(header)
        f.write(contents)

Writing ../data/who.population.txt
Writing ../data/who.life_expectancy_male.txt
Writing ../data/who.life_expectancy_female.txt
Writing ../data/who.life_expectancy.txt
Writing ../data/who.life_expectancy_healthy.txt
Writing ../data/who.maternal_mortality.txt
Writing ../data/who.attended_births.txt
Writing ../data/who.under_five_mortality.txt
Writing ../data/who.neonatal_moratlity.txt
Writing ../data/who.hiv_infections.txt
Writing ../data/who.tb_indicence.txt
Writing ../data/who.malaria_incidence.txt
Writing ../data/who.hepatitis_vaccine.txt
Writing ../data/who.ntd_interventions.txt
Writing ../data/who.early_disease_deaths.txt
Writing ../data/who.suicide_moratlity.txt
Writing ../data/who.alcohol_consumption.txt
Writing ../data/who.traffic_mortality.txt
Writing ../data/who.family_planning.txt
Writing ../data/who.adolescent_births.txt
Writing ../data/who.air_pollution_mortality.txt
Writing ../data/who.wash_mortality.txt
Writing ../data/who.poisoning_mortality.txt
Writing ../data/who.smoking_male.txt
Writing ../data/who.smoking_female.txt
Writing ../data/who.dpt_immunization.txt
Writing ../data/who.health_and_research.txt
Writing ../data/who.health_professionals.txt
Writing ../data/who.score_avg.txt
Writing ../data/who.govt_expendature.txt
Writing ../data/who.child_stunting.txt
Writing ../data/who.child_wasting.txt
Writing ../data/who.child_overweight.txt
Writing ../data/who.clean_water.txt
Writing ../data/who.sanitation.txt
Writing ../data/who.clean_fuels.txt
Writing ../data/who.particulate_matter.txt
Writing ../data/who.natural_disasters.txt
Writing ../data/who.homicide.txt
Writing ../data/who.conflict_deaths.txt
Writing ../data/who.cause_of_death_known.txt

In [5]:
! head ../data/who.life_expectancy_male.txt

# "description": 'Life expectancy, \nmale (2015)'
# "name": "life_expectancy_male"
# "units": "years"
59.3
75.1
73.8
nan
50.9
74.1
72.7

In [6]:
repr(descriptions[i])

"'Cause of death known'"

In [7]:
descriptions[i]

'Cause of death known'